steps:
  - name: gcr.io/cloud-builders/docker
    id: "build onfirst"
    args: ["build","-t","gcr.io/$PROJECT_ID/onfirst:$SHORT_SHA","."]
    dir: "src/onfirst"
    waitFor: ['-']

  - name: gcr.io/cloud-builders/docker
    id: "build onsecond"
    args: ["build","-t","gcr.io/$PROJECT_ID/onsecond:$SHORT_SHA","."]
    dir: "src/onsecond"
    waitFor: ['-']

  - name: gcr.io/cloud-builders/docker
    args: [
      "push",
      "gcr.io/$PROJECT_ID/onfirst:$SHORT_SHA",
      ]
    waitFor: ["build onfirst"]

  - name: gcr.io/cloud-builders/docker
    args: [
      "push",
      "gcr.io/$PROJECT_ID/onsecond:$SHORT_SHA",
      ]
    waitFor: ["build onsecond"]

  - name: hashicorp/terraform:0.12.20
    entrypoint: 'terraform'
    args: ['init','-backend-config=bucket=iac-for-serverless-tfstate']
  
  - name: hashicorp/terraform:0.12.20
    entrypoint: 'terraform'
    args: [
        "apply", "-auto-approve",
        "-var","project_id=$PROJECT_ID",
        "-var",'service_names=["onfirst","onsecond"]',
        "-var","image_tag=$SHORT_SHA"
    ]