steps:
  - name: gcr.io/cloud-builders/docker
    id: "build hello"
    args: ["build","-t","gcr.io/$PROJECT_ID/hello:$SHORT_SHA","."]
    dir: "src/hello"
    waitFor: ['-']

  - name: gcr.io/cloud-builders/docker
    id: "build goodbye"
    args: ["build","-t","gcr.io/$PROJECT_ID/goodbye:$SHORT_SHA","."]
    dir: "src/hello"
    waitFor: ['-']

  - name: gcr.io/cloud-builders/docker
    args: [
      "push",
      "gcr.io/$PROJECT_ID/hello:$SHORT_SHA",
      ]
    waitFor: ["build hello"]

  - name: gcr.io/cloud-builders/docker
    args: [
      "push",
      "gcr.io/$PROJECT_ID/goodbye:$SHORT_SHA",
      ]
    waitFor: ["build goodbye"]

  - name: hashicorp/terraform:0.12.20
    entrypoint: 'terraform'
    args: ['init','-backend-config=bucket=iac-for-serverless-tfstate']
  
  - name: hashicorp/terraform:0.12.20
    entrypoint: 'terraform'
    args: [
        "apply", "-auto-approve",
        "-var","project_id=$PROJECT_ID",
        "-var",'service_names=["hello","goodbye"]',
        "-var","image_tag=$SHORT_SHA"
    ]